name: Build and Push Container

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      image:
        type: string
        required: false
        default: setle/$GITHUB_REPOSITORY
      registry:
        type: string
        required: false
        default: registry.digitalocean.com
      push:
        type: boolean
        required: false
        default: true

jobs:
  build-code:
    name: Build & test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Lint and verify
        run: yarn lint && yarn test

      - name: Build application
        run: yarn build

      - name: E2E test
        run: yarn test:e2e

      - name: Cleanup dev dependencies
        run: yarn install --production

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .env.vault
            node_modules/
            dist/

  build-container:
    name: Build container
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Log in to Container Registry
        if: inputs.push
        run: echo "${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}" | podman login -u "${{secrets.DIGITALOCEAN_REGISTRY_USER}}" --password-stdin ${{ inputs.registry }}

      # Build the Podman image
      - name: Build Podman image
        run: podman build -t ${{ inputs.registry }}/${{ inputs.image }}:$GITHUB_SHA .

      # Push the Podman image
      - name: Push Podman image
        if: inputs.push
        run: podman push ${{ inputs.registry }}/${{ inputs.image }}:$GITHUB_SHA