name: Deploy Environment

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      environment:
        type: string
        required: true
      image:
        type: string
        required: false
        default: setle/$GITHUB_REPOSITORY
      registry:
        type: string
        required: false
        default: registry.digitalocean.com

jobs:
  changelog:
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:62f9d6b4636df57db3747a31db24d1f134b8abb4
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    environment: ${{ inputs.environment }} # only add environment on first job of deployment to avoid asking for approval on every job
    permissions:
      deployments: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify Slack
        run: java -jar /changelog.jar release --application=$GITHUB_REPOSITORY --environment=${{ inputs.environment }} --repository=$GITHUB_WORKSPACE --github-token=${{ secrets.GITHUB_TOKEN }} --before-deploy=true --github-repository=$GITHUB_REPOSITORY --slack-token=${{ secrets.SLACK_TOKEN }} --slack-channel=poc-ci-cd
  deploy:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        run: echo "${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}" | podman login -u "${{secrets.DIGITALOCEAN_REGISTRY_USER}}" --password-stdin ${{ inputs.registry }}

      - name: Tag Podman image
        run: |
          podman pull ${{ inputs.registry }}/${{ inputs.image }}:$GITHUB_SHA
          podman tag ${{ inputs.registry }}/${{ inputs.image }}:$GITHUB_SHA ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.environment }}

      - name: Push Podman image
        run: podman push ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.environment }}