name: Deployment Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test-code:
    uses: ./.github/workflows/job_build_and_test_code.yml

  build-and-push-container:
    needs: build-and-test-code
    uses: ./.github/workflows/job_build_and_push_container.yml
    secrets: inherit