name: Main Workflow

on:
  push:
    branches:
    - main

jobs:
  build-and-test-code:
    name: Build & test app
    uses: ./.github/workflows/job_build_and_test_code.yml

  build-and-push-container:
    name: Build & push container
    needs: build-and-test-code
    uses: ./.github/workflows/job_build_and_push_container.yml
    secrets: inherit

  generate-development-changelog:
    name: Changelog development
    needs: build-and-push-container
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: development
    secrets: inherit

  deploy-to-development:
    name: Deploy development
    needs: generate-development-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: development
    secrets: inherit

  generate-staging-changelog:
    name: Changelog staging
    needs: deploy-to-development
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: staging
    secrets: inherit

  deploy-to-staging:
    name: Deploy staging
    needs: generate-staging-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: staging
    secrets: inherit

  generate-production-changelog:
    name: Changelog production
    needs: deploy-to-staging
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: production
    secrets: inherit

  deploy-to-production:
    name: Deploy production
    needs: generate-production-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: production
    secrets: inherit