name: Main Workflow

on:
  push:
    branches:
    - main

permissions:
  deployments: read

jobs:
  build-and-push-container:
    name: Build application
    uses: ./.github/workflows/build_application.yml
    secrets: inherit

  deploy-development:
    name: Deploy development
    needs: build-and-push-container
    uses: ./.github/workflows/deploy_application.yml
    with:
      environment: development
    secrets: inherit

  deploy-staging:
    name: Deploy staging
    needs: deploy-development
    uses: ./.github/workflows/deploy_application.yml
    with:
      environment: staging
    secrets: inherit

  deploy-production:
    name: Deploy production
    needs: deploy-staging
    uses: ./.github/workflows/deploy_application.yml
    with:
      environment: production
    secrets: inherit