name: Main Workflow

on:
  push:
    branches:
    - main

jobs:
  build-and-test-code:
    name: Build & test application
    runs-on: ubuntu-latest
    steps:
      - name: Build & Test Code
        uses: ./.github/workflows/action_build_and_test_code.yml

  build-and-push-container:
    name: Build & push container
    runs-on: ubuntu-latest
    steps:
      - name: Build Container
        uses: ./.github/workflows/action_build_and_push_container.yml

  generate-development-changelog:
    name: Generate development changelog
    needs: build-and-push-container
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: development
    secrets: inherit

  deploy-to-development:
    name: Deploy development
    needs: generate-development-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: development
    secrets: inherit

  generate-staging-changelog:
    name: Generate staging changelog
    needs: deploy-to-development
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: staging
    secrets: inherit

  deploy-to-staging:
    name: Deploy staging
    needs: generate-staging-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: staging
    secrets: inherit

  generate-production-changelog:
    name: Generate production changelog
    needs: deploy-to-staging
    uses: ./.github/workflows/job_generate_changelog.yml
    with:
      environment: production
    secrets: inherit

  deploy-to-production:
    name: Deploy production
    needs: generate-production-changelog
    uses: ./.github/workflows/job_deploy_environment.yml
    with:
      environment: production
    secrets: inherit