name: Deploy Environment

on:
  workflow_call: # Makes this workflow reusable
    inputs:
      environment:
        type: string
        required: true
      environment_next:
        type: string
        required: false
      persist:
        type: boolean
        required: false
        default: false
      persist_next:
        type: boolean
        required: false
        default: false
      commit:
        type: string
        required: false
        default: $GITHUB_SHA
      pull_request:
        type: string
        required: false
      image:
        type: string
        required: false
        default: setle/$GITHUB_REPOSITORY
      registry:
        type: string
        required: false
        default: registry.digitalocean.com

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:608c196be7402dd9d253d625b7c6c2237bffb566
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify Slack
        run: |
          java -jar /changelog.jar release \
            --application=$GITHUB_REPOSITORY \
            --environment=${{ inputs.environment }} \
            --environment-next=${{ inputs.environment_next }} \
            --release-persist=${{ inputs.persist }} \
            --release-next-persist=${{ inputs.persist_next }} \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --github-repository=$GITHUB_REPOSITORY \
            --github-pull-request=${{ inputs.pull_request }} \
            --current-commit=${{ inputs.commit }} \
            --slack-token=${{ secrets.SLACK_TOKEN }} \
            --slack-channel=poc-ci-cd