name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened # Trigger only on PR events

jobs:
  build-container:
    name: Build application
    uses: ./.github/workflows/build_application.yml
    secrets: inherit
    with:
      push: ${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') }}
      # for hotfix branches we don't use GITHUB_SHA which is the commit on the merge branch
      # or else we'd be adding all changes from the latest commit of the main branch to production too
      commit: ${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') && github.event.pull_request.head.sha || github.sha }}

  verify-changelog:
    name: Verify changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:608c196be7402dd9d253d625b7c6c2237bffb566
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify commits for changelog entries
        run: |
          java -jar /changelog.jar verify-changelog \
            --application=$GITHUB_REPOSITORY \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --github-repository=$GITHUB_REPOSITORY \
            --github-pull-request=${{ github.event.pull_request.number }}

  deploy-production:
    if: "startsWith(github.event.pull_request.head.ref, 'hotfix/')"
    name: Deploy production
    needs: build-container
    uses: ./.github/workflows/deploy_application.yml
    with:
      environment: production
      commit: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  post-deploy-production:
    if: "startsWith(github.event.pull_request.head.ref, 'hotfix/')"
    name: Post-Deploy production
    needs: deploy-production
    uses: ./.github/workflows/post_deploy_application.yml
    with:
      environment: production
      persist: true
      commit: ${{ github.event.pull_request.head.sha }}
      pull_request: ${{ github.event.pull_request.number }}
    secrets: inherit
