name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened # Trigger only on PR events

jobs:
  build-container:
    if: "!startsWith(github.event.pull_request.head.ref, 'hotfix/')" # Exclude PRs from 'hotfix/' branches (handled in hotfix workflow)
    name: Build application
    uses: ./.github/workflows/build_application.yml
    secrets: inherit
    with:
      push: false

  verify-changelog:
    name: Verify changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:6012152156f337cab83716e648a06114b23a3c24
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify commits for changelog entries
        run: |
          java -jar /changelog.jar verify-changelog \
            --application=$GITHUB_REPOSITORY \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --github-repository=$GITHUB_REPOSITORY \
            --github-pull-request=${{ github.event.pull_request.number }}
