name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened # Trigger only on PR events
    branches-ignore:
      - 'hotfix/**'

jobs:
  build-container:
    name: Build application
    uses: ./.github/workflows/build_application.yml
    secrets: inherit
    with:
      push: false

  verify-changelog:
    name: Verify changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:cb6caced18fc680aab2c91e5992abe5ba6683a25
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify commits for changelog entries
        run: |
          java -jar /changelog.jar verify-changelog \
            --application=$GITHUB_REPOSITORY \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --github-repository=$GITHUB_REPOSITORY \
            --github-pull-request=${{github.event.pull_request.number}}
