name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened # Trigger only on PR events

jobs:
  build-and-test-code:
    name: Build & test application
    runs-on: ubuntu-latest
    if: "! startsWith(github.head_ref, 'hotfix/')" # Exclude branches starting with 'hotfix/'
    steps:
      - name: Build & Test Code
        uses: ./.github/workflows/action_build_and_test_code.yml

  build-container:
    name: Build container
    runs-on: ubuntu-latest
    if: "! startsWith(github.head_ref, 'hotfix/')" # Exclude branches starting with 'hotfix/'
    steps:
      - name: Build Container
        uses: ./.github/workflows/action_build_and_push_container.yml
        with:
          push: false