name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened # Trigger only on PR events

jobs:
  build-container:
    name: Build application
    uses: ./.github/workflows/build_application.yml
    if: "! startsWith(github.head_ref, 'hotfix/')" # Exclude branches starting with 'hotfix/'
    secrets: inherit
    with:
      push: false

  verify-changelog:
    name: Verify changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.digitalocean.com/setle/setlebe/setle-changelog:3435e970638b1f330543116c5b5f1a27f8efd697
      credentials:
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '150' # necessary to find changelog entries in commits, or else it will only look at the last commit
      - name: Verify commits for changelog entries
        run: java -jar /changelog.jar verify-changelog --application=$GITHUB_REPOSITORY --github-token=${{ secrets.GITHUB_TOKEN }} --github-repository=$GITHUB_REPOSITORY --current-commit=${{github.event.pull_request.head.sha}}
