name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened # Trigger only on PR events

jobs:
  build-container:
    name: Build application
    uses: build_application.yml
    if: "! startsWith(github.head_ref, 'hotfix/')" # Exclude branches starting with 'hotfix/'
    secrets: inherit
    with:
      push: false